---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zwierzeta-html
  namespace: envoy-ingress
data:
  landing.html: |
    <h1>Welcome to Orion Platform</h1>
    <img src="https://sentiwiki.copernicus.eu/__attachments/50561026/image-20231021-065335.png?inst-v=f449a58f-77a5-411d-952f-30467b0f995b" style="max-width: 100%; height: auto;"/>
    <p>Available satelite images:</p>
    <ul>
      <li><a href="http://sentinel3b.envoy_zwierzaki.local">Site about Sentinel-3B</a></li>
      <li><a href="http://sentinel3a.envoy_zwierzaki.local">Site about Sentinel-3A</a></li>
      <li><a href="http://sentinel2a.envoy_zwierzaki.local">Site about Sentinel-2A</a></li>
      <li><a href="http://sentinel1a.envoy_zwierzaki.local">Site about Sentinel-1A</a></li>
    </ul>
  sentinel3b.html: |
    <h1>Sentinel-3B</h1>
    <img src="https://eo.belspo.be/sites/default/files/styles/xlarge/public/satellites/224._sentinel-3b.jpg?itok=1dSvqFpS" alt="Sentinel-3B" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="https://eo.belspo.be/en/satellites-and-sensors/sentinel-3b">More info here</a></li>
      <li><a href="http://envoy_zwierzaki.local">Back to main site</a></li>
    </ul>
  sentinel3a.html: |
    <h1>Sentinel-3A</h1>
    <img src="https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2016/01/copernicus_sentinel-3/15758903-1-eng-GB/Copernicus_Sentinel-3_pillars.jpg" alt="Sentinel-3A" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-3/Rise_and_shine_for_Sentinel-3A">More info here</a></li>
      <li><a href="http://envoy_zwierzaki.local">Back to main site</a></li>
    </ul>
  sentinel2a.html: |
    <h1>Sentinel-2A</h1>
    <img src="https://esoc.esa.int/sites/default/files/Sentinel-2_pillars%20916x700_0.jpg" alt="Sentinel-2A" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="https://esoc.esa.int/content/sentinel-2a">More info here</a></li>
      <li><a href="http://envoy_zwierzaki.local">Back to main site</a></li>
    </ul>
  sentinel1a.html: |
    <h1>Sentinel-1A</h1>
    <img src="https://esoc.esa.int/sites/default/files/Sentinel-1_pillars%20916x700_0.jpg" alt="Sentinel-1A" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="https://esoc.esa.int/content/sentinel-1a">More info here</a></li>
      <li><a href="http://envoy_zwierzaki.local">Back to main site</a></li>
    </ul>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-html
  namespace: envoy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-html
  template:
    metadata:
      labels:
        app: landing-html
    spec:
      containers:
        - name: nginx
          image: {{ .Values.htmlImage }}
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/landing.html /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: html
              mountPath: /mnt
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: zwierzeta-html
            items:
              - key: landing.html
                path: landing.html
---
apiVersion: v1
kind: Service
metadata:
  name: landing-html
  namespace: envoy-ingress
spec:
  selector:
    app: landing-html
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- range .Values.zwierzeta }}
{{- if .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-html
  namespace: envoy-ingress
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}-html
  template:
    metadata:
      labels:
        app: {{ .name }}-html
        role: zwierzak-html
    spec:
      containers:
        - name: nginx
          image: {{ $.Values.htmlImage }}
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/{{ .name }}.html /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: html
              mountPath: /mnt
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: zwierzeta-html
            items:
              - key: {{ .name }}.html
                path: {{ .name }}.html
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-html
  namespace: envoy-ingress
spec:
  selector:
    app: {{ .name }}-html
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-bootstrap
  namespace: envoy-ingress
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_http
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: landing
                  domains: ["envoy_zwierzaki.local"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: landing_html
                {{- range .Values.zwierzeta }}
                {{- if .name }}
                - name: {{ .name }}
                  domains: ["{{ .name }}.envoy_zwierzaki.local"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: {{ .name }}_html
                {{- end }}
                {{- end }}
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: landing_html
        type: LOGICAL_DNS
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: landing_html
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: landing-html.envoy-ingress.svc.cluster.local
                    port_value: 80
      {{- range .Values.zwierzeta }}
      {{- if .name }}
      - name: {{ .name }}_html
        type: LOGICAL_DNS
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{ .name }}_html
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .name }}-html.envoy-ingress.svc.cluster.local
                    port_value: 80
      {{- end }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ingress
  namespace: envoy-ingress
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: {{ .Values.envoyImage }}
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
          ports:
            - containerPort: 80
      volumes:
        - name: config
          configMap:
            name: envoy-bootstrap
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ingress
  namespace: envoy-ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.18.215
  selector:
    app: envoy
  ports:
    - port: 80
      targetPort: 10080
