---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zwierzeta-html
  namespace: envoy-ingress
data:
  landing.html: |
    <h1>Welcome to Orion Platform</h1>
    <img src="https://sentiwiki.copernicus.eu/__attachments/50561026/image-20231021-065335.png?inst-v=f449a58f-77a5-411d-952f-30467b0f995b" style="max-width: 100%; height: auto;"/>
    <p>Available satelite images:</p>
    <ul>
      <li><a href="http://sentinel1a.envoy_zwierzaki.local">Site about Sentinel-1A</a></li>
      <li><a href="http://pies.envoy_zwierzaki.local">Strona o psie</a></li>
      <li><a href="http://pies.envoy_zwierzaki.local">Strona o psie</a></li>
      <li><a href="http://kot.envoy_zwierzaki.local">Strona o kocie</a></li>
      <li><a href="http://zolw.envoy_zwierzaki.local">Strona o zolwiu</a></li>
      <li><a href="http://lew.envoy_zwierzaki.local">Strona o lwie</a></li>
      <li><a href="http://kaczka.envoy_zwierzaki.local">Strona o kaczce</a></li>
      <li><a href="http://lis.envoy_zwierzaki.local">Strona o lisie</a></li>
      <li><a href="http://lama.envoy_zwierzaki.local">Strona o lamie</a></li>
      <li><a href="http://chomik.envoy_zwierzaki.local">Strona o chomiku</a></li>
      <li><a href="http://leopard.envoy_zwierzaki.local">Strona o leopardzie</a></li>
      <li><a href="http://jez.envoy_zwierzaki.local">Strona o jezu</a></li>
    </ul>
  sentinel1a.html: |
    <h1>Sentinel-1A</h1>
    <img src="https://esoc.esa.int/sites/default/files/Sentinel-1_pillars%20916x700_0.jpg" alt="Sentinel-1A" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Back to main site</a></li>
    </ul>
  kot.html: |
    <h1>To jest kot</h1>
    <img src="https://cdn.pixabay.com/photo/2017/11/09/21/41/cat-2934720_1280.jpg" alt="Kot" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  pies.html: |
    <h1>To jest pies</h1>
    <img src="https://cdn.pixabay.com/photo/2018/03/31/06/31/dog-3277414_960_720.jpg" alt="Pies" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  zolw.html: |
    <h1>To jest zolw</h1>
    <img src="https://media.istockphoto.com/id/2150060570/pl/zdj%C4%99cie/zielony-%C5%BC%C3%B3%C5%82w-morski-sun%C4%85cy-po-ciemnoniebieskiej-tropikalnej-wodzie.jpg?s=612x612&w=is&k=20&c=cp5IuwKD-akrQGaETsUdNDLjQMjf54PjPBH7SANX9Ik=" alt="Zolw" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  lew.html: |
    <h1>To jest lis</h1>
    <img src="https://media.istockphoto.com/id/1375721633/pl/zdj%C4%99cie/m%C4%99skie-lwy-pieszczotliwie-pozdrawiam.jpg?s=612x612&w=is&k=20&c=jHLT4Cw_eC8wJfTPsNBgUuQn8gdDR0kw35yCXR3vmxc=" alt="lis"style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  kaczka.html: |
    <h1>To jest kaczka</h1>
    <img src="https://media.istockphoto.com/id/133976455/pl/zdj%C4%99cie/grupa-z-kaczki.jpg?s=612x612&w=is&k=20&c=WeDf2kO6RQV0tWynHCImHWZ3Q_BtL97CE-XtcI6FYdk=" alt="kaczka" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  lis.html: |
    <h1>To jest lis</h1>
    <img src="https://media.istockphoto.com/id/108200397/pl/zdj%C4%99cie/fox-w-jesie%C5%84-g%C3%B3rski.jpg?s=612x612&w=is&k=20&c=1_h0TrPS8t1e5ZovbFQq4TKoEAE_E5pYadYZhEjZksI=" alt="lis" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  lama.html: |
    <h1>To jest lama</h1>
    <img src="https://cdn.pixabay.com/photo/2021/11/09/18/51/llama-6782140_960_720.jpg" alt="lama" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  chomik.html: |
    <h1>To jest chomik</h1>
    <img src="https://cdn.pixabay.com/photo/2020/06/11/18/18/guinea-pig-5287749_960_720.jpg" alt="chomik" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  leopard.html: |
    <h1>To jest leopard</h1>
    <img src="https://cdn.pixabay.com/photo/2012/03/01/00/28/animal-19621_960_720.jpg" alt="leopard"style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
  jez.html: |
    <h1>To jest jez</h1>
    <img src="https://cdn.pixabay.com/photo/2016/08/10/21/58/hedgehog-1584351_960_720.jpg" alt="jez" style="max-width: 100%; height: auto;"/>
    <ul>
      <li><a href="http://envoy_zwierzaki.local">Powrot do spisu tresci</a></li>
    </ul>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-html
  namespace: envoy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-html
  template:
    metadata:
      labels:
        app: landing-html
    spec:
      containers:
        - name: nginx
          image: {{ .Values.htmlImage }}
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/landing.html /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: html
              mountPath: /mnt
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: zwierzeta-html
            items:
              - key: landing.html
                path: landing.html
---
apiVersion: v1
kind: Service
metadata:
  name: landing-html
  namespace: envoy-ingress
spec:
  selector:
    app: landing-html
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- range .Values.zwierzeta }}
{{- if .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-html
  namespace: envoy-ingress
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}-html
  template:
    metadata:
      labels:
        app: {{ .name }}-html
        role: zwierzak-html
    spec:
      containers:
        - name: nginx
          image: {{ $.Values.htmlImage }}
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/{{ .name }}.html /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: html
              mountPath: /mnt
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: zwierzeta-html
            items:
              - key: {{ .name }}.html
                path: {{ .name }}.html
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-html
  namespace: envoy-ingress
spec:
  selector:
    app: {{ .name }}-html
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-bootstrap
  namespace: envoy-ingress
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_http
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: landing
                  domains: ["envoy_zwierzaki.local"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: landing_html
                {{- range .Values.zwierzeta }}
                {{- if .name }}
                - name: {{ .name }}
                  domains: ["{{ .name }}.envoy_zwierzaki.local"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: {{ .name }}_html
                {{- end }}
                {{- end }}
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: landing_html
        type: LOGICAL_DNS
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: landing_html
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: landing-html.envoy-ingress.svc.cluster.local
                    port_value: 80
      {{- range .Values.zwierzeta }}
      {{- if .name }}
      - name: {{ .name }}_html
        type: LOGICAL_DNS
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{ .name }}_html
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .name }}-html.envoy-ingress.svc.cluster.local
                    port_value: 80
      {{- end }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ingress
  namespace: envoy-ingress
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: {{ .Values.envoyImage }}
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
          ports:
            - containerPort: 80
      volumes:
        - name: config
          configMap:
            name: envoy-bootstrap
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ingress
  namespace: envoy-ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.18.215
  selector:
    app: envoy
  ports:
    - port: 80
      targetPort: 10080
